apiVersion: unagex.com/v1
kind: Metabase
metadata:
  name: metabase-sts-service
spec:
  metabase:
    image: "py846260131/metabase:latest"
    imagePullPolicy: "IfNotPresent"
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
  db:
    # image: "postgres:latest"
    # imagePullPolicy: "IfNotPresent"
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
    volume:
      # storageClassName: standard
      size: 10Gi