apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics.fullname" . }}
  labels:
    {{- include "metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "metrics.selectorLabels" . | nindent 4 }}
